const supabaseUrl = 'https://fwwzzuyzuxdqfftofmmn.supabase.co';
const supabaseKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3d3p6dXl6dXhkcWZmdG9mbW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTExNjMzNTMsImV4cCI6MjAyNjczOTM1M30.7RnRBCO3WEM7gUSG_JFDS6DZqJwAAOCfhMacJTuOBhM';
